/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Serge Zvenigorodsky
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameMenu = new javax.swing.JPopupMenu();
        gunMenu = new javax.swing.JMenu();
        shotMenu = new javax.swing.JMenu();
        generalMenu = new javax.swing.JMenuItem();
        gameDisplay = new javax.swing.JInternalFrame();

        gameMenu.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                gameMenuMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        gunMenu.setText("jMenu1");
        gameMenu.add(gunMenu);

        shotMenu.setText("jMenu1");
        gameMenu.add(shotMenu);

        generalMenu.setText("jMenuItem1");
        generalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalMenuActionPerformed(evt);
            }
        });
        gameMenu.add(generalMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gameDisplay.setClosable(true);
        gameDisplay.setMaximizable(true);
        gameDisplay.setResizable(true);
        gameDisplay.setVisible(true);

        javax.swing.GroupLayout gameDisplayLayout = new javax.swing.GroupLayout(gameDisplay.getContentPane());
        gameDisplay.getContentPane().setLayout(gameDisplayLayout);
        gameDisplayLayout.setHorizontalGroup(
            gameDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        gameDisplayLayout.setVerticalGroup(
            gameDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameDisplay)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameDisplay)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameMenuMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_gameMenuMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameMenuMenuKeyPressed

    private void generalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame gameDisplay;
    private javax.swing.JPopupMenu gameMenu;
    private javax.swing.JMenuItem generalMenu;
    private javax.swing.JMenu gunMenu;
    private javax.swing.JMenu shotMenu;
    // End of variables declaration//GEN-END:variables
}
